attrs:
  title: MHKiT Tidal Module Example
  description:
    The following example will familiarize the user with the MHKiT tidal module by
    stepping through the calculation of the velocity duration curve.
  location_id: mhkit
  dataset_name: tidal_example
  data_level: a1
  # qualifier:
  # temporal:
  # institution:

coords:
  time:
    dims: [time]
    dtype: datetime64[s]
    attrs:
      long_name: Time
      standard_name: time
      units: Seconds since 1970-01-01 00:00:00 UTC
      timezone: UTC

data_vars:
  water_speed:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Water Speed
      standard_name: sea_water_speed
      units: m/s
  water_direction:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Water Direction
      standard_name: sea_water_to_direction
      units: degT
  exceed_prob:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Exceedance Probability
      units: percent
