classname: pipelines.tidal_example.pipeline.TidalExample

triggers:
  # DEVELOPER: Update regex patterns that should trigger this pipeline
  - .*mhkit.*\.csv

retriever:
  path: pipelines/tidal_example/config/retriever.yaml

dataset:
  path: pipelines/tidal_example/config/dataset.yaml

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml
