classname: pipelines.tidal_example.pipeline.TidalExample

triggers:
  - .*noaa.*\.json

retriever:
  path: pipelines/tidal_example/config/retriever.yaml

dataset:
  path: pipelines/tidal_example/config/dataset.yaml

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml
