classname: tsdat.io.retrievers.DefaultRetriever
readers:
  .*:
    classname: pipelines.tidal_example.readers.NOAAjsonReader

coords:
  time:
    name: time
    data_converters:
      - classname: tsdat.io.converters.StringToDatetime
        format: "%Y-%m-%d %H:%M:%S"
        timezone: UTC

data_vars:
  water_speed:
    name: s
    data_converters:
      - classname: tsdat.io.converters.UnitsConverter
        input_units: cm/s

  water_direction:
    name: d
