classname: pipelines.wave_example.pipeline.WaveExample

triggers:
  - .*\.zip

retriever:
  path: pipelines/wave_example/config/retriever.yaml

dataset:
  path: pipelines/wave_example/config/dataset.yaml

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml
