classname: tsdat.io.retrievers.DefaultRetriever
readers:
  .*:
    classname: pipelines.river_example.readers.USGSjsonReader

coords:
  time:
    name: time
    data_converters:
      - classname: tsdat.io.converters.StringToDatetime
        timezone: UTC

data_vars:
  discharge:
    name: Discharge, cubic feet per second
    data_converters:
      - classname: tsdat.io.converters.UnitsConverter
        input_units: ft^3/s
