attrs:
  title: MHKiT Wave Module Example
  description:
    The following example runs an application of the MHKiT wave module to 1. read in
    NDBC data, 2. compute metrics from spectral data, 3. generate a capture length
    matrix, 4. calculate MAEP, and 5. plot the metrics.
  location_id: mhkit
  dataset_name: wave_module_example
  data_level: a1
  # qualifier:
  # temporal:
  # institution:

coords:
  time:
    dims: [time]
    dtype: datetime64[ms]
    attrs:
      units: Seconds since 1970-01-01 00:00:00 UTC
      timezone: UTC

  frequency:
    dims: [frequency]
    dtype: float32
    attrs:
      long_name: band center frequency
      units: Hz
      standard_name: wave_frequency

  time_device:
    dims: [time_device]
    dtype: datetime64[ms]
    attrs:
      units: Seconds since 1970-01-01 00:00:00 UTC
      timezone: UTC

data_vars:
  wave_hs:
    dims: [time]
    dtype: float32
    attrs:
      long_name: significant wave height
      units: m
      standard_name: sea_surface_wave_significant_height
      valid_min: 0.0
      valid_max: 20.0
      ncei_name: WAVE HEIGHT - SIGNIFICANT

  wave_tp:
    dims: [time]
    dtype: float32
    attrs:
      long_name: peak wave period
      units: s
      standard_name: sea_surface_wave_period_at_variance_spectral_density_maximum
      valid_min: 0.0
      valid_max: 40.0
      ncei_name: WAVE - PEAK PERIOD

  wave_ta:
    dims: [time]
    dtype: float32
    attrs:
      long_name: average wave period
      units: s
      standard_name: sea_surface_wave_mean_period_from_variance_spectral_density_first_frequency_moment
      valid_min: 0.0
      valid_max: 40.0
      ncei_name: WAVE PERIOD - AVERAGE

  wave_te:
    dims: [time]
    dtype: float32
    attrs:
      long_name: wave energy period
      units: s
      standard_name: sea_surface_wave_mean_period_from_variance_spectral_density_inverse_frequency_moment
      valid_min: 0.0
      valid_max: 40.0

  wave_tz:
    dims: [time]
    dtype: float32
    attrs:
      long_name: spectral zero-upcross wave period
      units: s
      standard_name: sea_surface_wave_mean_period_from_variance_spectral_density_second_frequency_moment
      valid_min: 0.0
      valid_max: 40.0

  wave_energy_density:
    dims: [time, frequency]
    dtype: float32
    attrs:
      long_name: band energy density
      units: m^2 s
      standard_name: sea_surface_wave_variance_spectral_density
      valid_min: 0.0
      ncei_name: WAVE ENERGY - SPECTRAL VALUE

  wave_energy_flux:
    dims: [time]
    dtype: float32
    attrs:
      long_name: omnidirectional wave energy flux
      units: W/m
      valid_min: 0.0

  device_power:
    dims: [time_device]
    dtype: float32
    attrs:
      long_name: WEC mechanical power
      units: W
      valid_min: 0.0

  device_capture_length:
    dims: [time]
    dtype: float32
    attrs:
      long_name: WEC capture length
      units: m
      valid_min: 0.0

  device_maep:
    dims: []
    dtype: float32
    attrs:
      long_name: WEC mean annual energy production
      units: W
      valid_min: 0.0

  # wave_dp:
  #   dims: [time]
  #   dtype: float32
  #   attrs:
  #     long_name: peak wave direction
  #     units: degree_true
  #     standard_name: sea_surface_wave_from_direction
  #     valid_min: 0.0
  #     valid_max: 360.0
  #     ncei_name: WAVE DIRECTION

  # wave_spread:
  #   dims: [time, frequency]
  #   dtype: float32
  #   attrs:
  #     long_name: band directional spread
  #     units: deg
  #     valid_min: 0.0
  #     valid_max: 90.0
