attrs:
  # https://ioos.github.io/ioos-metadata/ioos-metadata-profile-v1-2.html
  # https://wiki.esipfed.org/Attribute_Convention_for_Data_Discovery_1-3
  # Dataset Description
  conventions: "CD-1.6, ACDD-1.3, IOOS-1.2"
  featureType: timeseries
  id: ADV
  infoURL: https://www.osti.gov/biblio/1842840
  license: Freely Distributed
  naming_authority: gov.pnnl.sequim
  standard_name_vocabulary: CF Standard Name Table v79

  title: MHKiT ADV Example
  description: >-
    Test data from a Nortek ADV
  keywords: water velocity, water direction, channel, marine
  # Attribution
  creator_country: USA
  #creator_email:
  creator_institution: National Renewable Energy Laboratory (NREL)
  creator_institution_url: https://www.nrel.gov/
  creator_sector: other
  creator_type: institution
  creator_url: https://www.nrel.gov/
  institution: National Renewable Energy Laboratory (NREL)
  publisher_country: USA
  #publisher_email:
  publisher_institution: National Renewable Energy Laboratory (NREL)
  publisher_url: https://www.nrel.gov/

  # Platform and Instrument
  platform: lander
  platform_vocabulary: https://mmisw.org/ont/ioos/platform
  instrument: In Situ/Laboratory Instruments > Current/Wind Meters > Current Meters
  instrument_vocabulary: GCMD Instrument Keywords #https://gcmd.earthdata.nasa.gov/KeywordViewer/
  make_model: Nortek ADV

  # Geospatial and Time
  geospatial_bounds: Point ((48.0804 -123.0449))
  geospatial_bounds_crs: "EPSG:4326"
  time_coverage_start: "2022-05-18T21:28:46"
  time_coverage_duration: "01:00:00"
  time_coverage_resolution: "00:00:00.500"

  # TSDAT specific parameters
  location_id: nrel
  dataset_name: adv
  data_level: b1

coords:
  time:
    dims: [time]
    dtype: datetime64[ms]
    attrs:
      units: Seconds since 1970-01-01 00:00:00
      long_name: Time
      standard_name: time
      timezone: UTC
      description: "Timestamp for data generated by ADCP beams 1-4"
      coverage_content_type: coordinate
  dir:
    dims: [dir]
    dtype: str
    attrs:
      long_name: Reference Frame
      units: "1"
      coverage_content_type: coordinate
  beam:
    dims: [beam]
    dtype: int
    attrs:
      long_name: Beam Reference Frame
      units: "1"
      coverage_content_type: coordinate
  inst:
    dims: [inst]
    dtype: str
    attrs:
      long_name: Instrument Reference Frame
      units: "1"
      coverage_content_type: coordinate
  earth:
    dims: [earth]
    dtype: str
    attrs:
      long_name: Earth Reference Frame
      units: "1"
      coverage_content_type: coordinate

data_vars:
  vel:
    dims: [dir, time]
    dtype: float32
    attrs:
      long_name: Sea Water Velocity
      units: m/s
      valid_min: -5
      valid_max: 5
  amp:
    dims: [beam, time]
    dtype: int
    attrs:
      long_name: Acoustic Signal Amplitude
      units: "1"
  corr:
    dims: [beam, time]
    dtype: int
    attrs:
      long_name: Acoustic Signal Correlation
      units: "%"
  U_mag:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Water Speed
      standard_name: sea_water_speed
      units: m/s
      valid_min: -5
      valid_max: 5
  U_dir:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Water Direction
      standard_name: sea_water_to_direction
      units: deg
  depth:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Water Depth
      standard_name: depth
      units: m
      positive: down
  water_density:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Water Density
      standard_name: sea_water_density
      description:
        "Water density from linear approximation of sea water equation of state"
      units: kg/m^3
  heading:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Heading
      standard_name: platform_orientation
      units: deg
      valid_min: -180
      valid_max: 180
  pitch:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Pitch
      standard_name: platform_pitch
      units: deg
      valid_min: -180
      valid_max: 180
  roll:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Roll
      standard_name: platform_roll
      units: deg
      valid_min: -180
      valid_max: 180
  orientmat:
    dims: [earth, inst, time]
    dtype: float32
    attrs:
      description: Earth (ENU) to instrument (XYZ) orientation matrix
      long_name: Orientation Matrix
      units: "1"
  beam2inst_orientmat:
    dims: [beam, inst]
    dtype: float32
    attrs:
      description: "Beam to instrument orientation matrix"
      units: "1"
  speed_of_sound:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Speed of Sound
      standard_name: speed_of_sound_in_sea_water
      units: m/s
  pressure:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Pressure
      standard_name: sea_water_pressure
      units: dbar
  temperature:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Temperature
      standard_name: sea_water_temperature
      units: degC
  error:
    dims: [time]
    dtype: int
    attrs:
      long_name: Error Code
      units: "1"
  status:
    dims: [time]
    dtype: uint32
    attrs:
      units: "1"
      long_name: Status Code
  orientation_down:
    dims: [time]
    dtype: int
    attrs:
      units: "1"
      long_name: Orientation Down
      description:
        True if ADV communications cable is pointed downwards, which is the opposite
        direction that the ADV probe is pointed
