classname: pipelines.power_example.pipeline.PowerExample

triggers:
  # DEVELOPER: Update regex patterns that should trigger this pipeline
  - .*mhkit.*\.csv

retriever:
  path: pipelines/power_example/config/retriever.yaml

dataset:
  path: pipelines/power_example/config/dataset.yaml

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml
